### ISSUE TITLE
createdby SYSTEM and not actual user in portal

### ISSUE THREAD

**Issue by AndrewElans** [GuidoPreite/DRB_XrmToolBox#4]
Great tool, Guido! I have a question which I hope you could enlighten on as I fail to find the answer.

I have custom table with user request data. When creating a record through DRB the record has actual user name filled in "Created By". However when running a webapi query from a portal, "Created By" becomes "SYSTEM" created.

In the portal I provided for associated table setup with "createdby@odata.bind": "/systemusers(<user guid here>)". The query runs with success, but "Created By" is still "SYSTEM". However, when the same query is run with "ownerid@odata.bind"..., "Owner" is filled with proper user name. 

I see that DRB query is sent directly to dataverse, but the portal query is done through portal webapi. I guess here comes the difference. But is it possible with the portal webapi fill in actual user in "Created By", "Created By (Delegate)" or other system fields?

Another thing I noticed when going to "https://MY_PORTAL.powerappsportals.com/_api/MY_CUSTOM_TABLE" is that only "ownerid" has property "Microsoft.Dynamics.CRM.associatednavigationproperty", and neither of "createdby", "createdonbehalfby", etc. have this property defined. Maybe here is the caveat and therefore I can associate only "ownerid" with actual user.

**Comment by GuidoPreite** [comment]
Hi @AndrewElans.
the two properties you mentioned (_createdby_ and  _createdonbehalfby_) are marked _False_ for the properties _IsValidForCreate_ and _IsValidForUpdate_ coming from the metadata. I am quite sure Dataverse REST Builder did not show you that two properties when you built the _Create_ request.

You can try with impersonation, you will need to copy the header from the jQuery syntax, the one called _MSCRMCallerID_ or the one called _CallerObjectId_ depending on the impersonation type you are doing, because in my tool when you generate the Portals syntax there is the following warning:

// WARNING: Portals doesn't support Impersonation

As I never tried the impersonation with the Portals API, because additional permissions are probably required in order to fill that field and the request may fail.

Let me know if this solves your question before I close this issue.
Thanks

**Comment by AndrewElans** [comment]
Thanks for your quick response. I didn't succeed with impersonation either. Header with "CallerObjectId" as well as "...@odata.bind" were included but nothing has changed in the result. Thanks anyway and please close the issue.
